import sys
import numpy as np
sys.path.append('../partools')
import parallel as par

def createResolvedVar(filtField,Case):
    # Preselect all the resolved variables
    ResolvedVar = []
    boxSizeH = Case['boxSizeH']
    boxSizeW = Case['boxSizeW']
    neighbourLevels = Case['neighbourLevels']

    if neighbourLevels>=0:
        ResolvedVar.append(filtField[:,:,0])
        ResolvedVar.append(filtField[:,:,1])
    if neighbourLevels>=1:
        paddingMax = max(boxSizeH,boxSizeW)
        tmp0H=np.pad(filtField[:,:,0],boxSizeH)
        tmp1H=np.pad(filtField[:,:,1],boxSizeH)
        tmp0W=np.pad(filtField[:,:,0],boxSizeW)
        tmp1W=np.pad(filtField[:,:,1],boxSizeW)
        tmp0M=np.pad(filtField[:,:,0],paddingMax)
        tmp1M=np.pad(filtField[:,:,1],paddingMax)
        ResolvedVar.append(np.roll(tmp0H,-boxSizeH,axis=0)[boxSizeH:-boxSizeH,boxSizeH:-boxSizeH])
        ResolvedVar.append(np.roll(tmp1H,-boxSizeH,axis=0)[boxSizeH:-boxSizeH,boxSizeH:-boxSizeH])
        ResolvedVar.append(np.roll(tmp0H,boxSizeH,axis=0)[boxSizeH:-boxSizeH,boxSizeH:-boxSizeH])
        ResolvedVar.append(np.roll(tmp1H,boxSizeH,axis=0)[boxSizeH:-boxSizeH,boxSizeH:-boxSizeH])
        ResolvedVar.append(np.roll(tmp0W,-boxSizeW,axis=1)[boxSizeW:-boxSizeW,boxSizeW:-boxSizeW])
        ResolvedVar.append(np.roll(tmp1W,-boxSizeW,axis=1)[boxSizeW:-boxSizeW,boxSizeW:-boxSizeW])
        ResolvedVar.append(np.roll(tmp0W,boxSizeW,axis=1)[boxSizeW:-boxSizeW,boxSizeW:-boxSizeW])
        ResolvedVar.append(np.roll(tmp1W,boxSizeW,axis=1)[boxSizeW:-boxSizeW,boxSizeW:-boxSizeW])
        #Corners
        ResolvedVar.append(np.roll(np.roll(tmp0M,-paddingMax,axis=0),-paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1M,-paddingMax,axis=0),-paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0M,paddingMax,axis=0),-paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1M,paddingMax,axis=0),-paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0M,paddingMax,axis=0),paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1M,paddingMax,axis=0),paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0M,-paddingMax,axis=0),paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1M,-paddingMax,axis=0),paddingMax,axis=1)[paddingMax:-paddingMax,paddingMax:-paddingMax])
    if neighbourLevels>=2:
        paddingMax = max(boxSizeH,boxSizeW)
        tmp0_2M=np.pad(filtField[:,:,0],2*paddingMax)
        tmp1_2M=np.pad(filtField[:,:,1],2*paddingMax)
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,-2*boxSizeH,axis=0),-boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,-2*boxSizeH,axis=0),-boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,-2*boxSizeH,axis=0),0,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,-2*boxSizeH,axis=0),0,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,-2*boxSizeH,axis=0),boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,-2*boxSizeH,axis=0),boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])

        ResolvedVar.append(np.roll(np.roll(tmp0_2M,2*boxSizeH,axis=0),-boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,2*boxSizeH,axis=0),-boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,2*boxSizeH,axis=0),0,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,2*boxSizeH,axis=0),0,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,2*boxSizeH,axis=0),boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,2*boxSizeH,axis=0),boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])

        ResolvedVar.append(np.roll(np.roll(tmp0_2M,boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,0,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,0,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,-boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,-boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])

        ResolvedVar.append(np.roll(np.roll(tmp0_2M,boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,0,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,0,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,-boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,-boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])

        ResolvedVar.append(np.roll(np.roll(tmp0_2M,-2*boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,-2*boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,2*boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,2*boxSizeH,axis=0),-2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,2*boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,2*boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp0_2M,-2*boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])
        ResolvedVar.append(np.roll(np.roll(tmp1_2M,-2*boxSizeH,axis=0),2*boxSizeW,axis=1)[2*paddingMax:-2*paddingMax,2*paddingMax:-2*paddingMax])

    return ResolvedVar

# Prestore the names of all the resolved variables
def createResolvedVarNames(Case):
    ResolvedVarNames=[]
    neighbourLevels = Case['neighbourLevels']
    if neighbourLevels>=0:
        # Level 0
        ResolvedVarNames.append('Uij')
        ResolvedVarNames.append('Vij')
    if neighbourLevels>=1:
        # Level 1
        ResolvedVarNames.append('Uipj')
        ResolvedVarNames.append('Vipj')
        ResolvedVarNames.append('Uimj')
        ResolvedVarNames.append('Vimj')
        ResolvedVarNames.append('Uijp')
        ResolvedVarNames.append('Vijp')
        ResolvedVarNames.append('Uijm')
        ResolvedVarNames.append('Vijm')
        # Corners
        ResolvedVarNames.append('Uipjp')
        ResolvedVarNames.append('Vipjp')
        ResolvedVarNames.append('Uimjp')
        ResolvedVarNames.append('Vimjp')
        ResolvedVarNames.append('Uimjm')
        ResolvedVarNames.append('Vimjm')
        ResolvedVarNames.append('Uipjm')
        ResolvedVarNames.append('Vipjm')
    if neighbourLevels>=2:
        # Level 2
        ResolvedVarNames.append('Uippjp')
        ResolvedVarNames.append('Vippjp')
        ResolvedVarNames.append('Uippj')
        ResolvedVarNames.append('Vippj')
        ResolvedVarNames.append('Uippjm')
        ResolvedVarNames.append('Vippjm')
    
        ResolvedVarNames.append('Uimmjp')
        ResolvedVarNames.append('Vimmjp')
        ResolvedVarNames.append('Uimmj')
        ResolvedVarNames.append('Vimmj')
        ResolvedVarNames.append('Uimmjm')
        ResolvedVarNames.append('Vimmjm')
    
        ResolvedVarNames.append('Uimjpp')
        ResolvedVarNames.append('Vimjpp')
        ResolvedVarNames.append('Uijpp')
        ResolvedVarNames.append('Vijpp')
        ResolvedVarNames.append('Uipjpp')
        ResolvedVarNames.append('Vipjpp')
    
        ResolvedVarNames.append('Uimjmm')
        ResolvedVarNames.append('Vimjmm')
        ResolvedVarNames.append('Uijmm')
        ResolvedVarNames.append('Vijmm')
        ResolvedVarNames.append('Uipjmm')
        ResolvedVarNames.append('Vipjmm')
        # Corners
        ResolvedVarNames.append('Uippjpp')
        ResolvedVarNames.append('Vippjpp')
        ResolvedVarNames.append('Uimmjpp')
        ResolvedVarNames.append('Vimmjpp')
        ResolvedVarNames.append('Uimmjmm')
        ResolvedVarNames.append('Vimmjmm')
        ResolvedVarNames.append('Uippjmm')
        ResolvedVarNames.append('Vippjmm')

    return ResolvedVarNames

# Create the stochastic estimation terms
def createSETerms(ResolvedVarNames,Case):
    # Terms are created as arrays of references to the resolved variable
    SETermsRef = []
    SEmodel = Case['SEmodel']
    if SEmodel>=1:
        ind = ResolvedVarNames.index('Uij')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vij')
        SETermsRef.append([ind, -1, -1, -1])
    if SEmodel>=2:
        ind = ResolvedVarNames.index('Uij')
        SETermsRef.append([ind, ind, -1, -1])
        ind = ResolvedVarNames.index('Vij')
        SETermsRef.append([ind, ind, -1, -1])
    if SEmodel>=3:
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vij')
        SETermsRef.append([ind1, ind2, -1, -1])
    if SEmodel>=4:
        ind = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind, -1, -1, -1])
    if SEmodel>=5:
        ind = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind, -1, -1, -1])
    if SEmodel>=6:
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, -1, -1])
    if SEmodel>=7:
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, -1, -1])
    if SEmodel>=8:
        ind = ResolvedVarNames.index('Uippjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vippjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uippj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vippj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uippjm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vippjm')
        SETermsRef.append([ind, -1, -1, -1])
    
        ind = ResolvedVarNames.index('Uimmjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimmjp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uimmj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimmj')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uimmjm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimmjm')
        SETermsRef.append([ind, -1, -1, -1])
    
        ind = ResolvedVarNames.index('Uimjpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimjpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uijpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vijpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uipjpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vipjpp')
        SETermsRef.append([ind, -1, -1, -1])
    
        ind = ResolvedVarNames.index('Uimjmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimjmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uijmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vijmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uipjmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vipjmm')
        SETermsRef.append([ind, -1, -1, -1])
    
    if SEmodel>=9:
    
        ind = ResolvedVarNames.index('Uippjpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vippjpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uimmjpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimmjpp')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uimmjmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vimmjmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Uippjmm')
        SETermsRef.append([ind, -1, -1, -1])
        ind = ResolvedVarNames.index('Vippjmm')
        SETermsRef.append([ind, -1, -1, -1])
    
    if SEmodel>=10:
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uippjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vippjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uippj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vippj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uippjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vippjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimmjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimmjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimmj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimmj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimmjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimmjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
    
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uippjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vippjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uippj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vippj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uippjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vippjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimmjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimmjp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimmj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimmj')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimmjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimmjm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
    
    
    if SEmodel>=11:
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uippjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vippjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uippjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vippjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimmjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimmjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimmjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimmjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uippjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vippjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uippjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vippjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimmjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimmjpp')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimmjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimmjmm')
        SETermsRef.append([ind1, ind2, -1, -1])
    
    if SEmodel>=12:
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipj')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimj')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
    
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipj')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimj')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
    
    
    if SEmodel>=13:
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjm')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjp')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjm')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjp')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
    if SEmodel>=14:
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjp')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjp')
        ind3 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipj')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipj')
        ind3 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vipjm')
        ind3 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijm')
        ind3 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjm')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjm')
        ind3 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimj')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimj')
        ind3 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vimjp')
        ind3 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Uij')
        ind2 = ResolvedVarNames.index('Vijp')
        ind3 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjp')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjp')
        ind3 = ResolvedVarNames.index('Vipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjp')
        ind3 = ResolvedVarNames.index('Uipj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipj')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipj')
        ind3 = ResolvedVarNames.index('Vipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipj')
        ind3 = ResolvedVarNames.index('Uipjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uipjm')
        ind3 = ResolvedVarNames.index('Vijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vipjm')
        ind3 = ResolvedVarNames.index('Uijm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijm')
        ind3 = ResolvedVarNames.index('Vimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijm')
        ind3 = ResolvedVarNames.index('Uimjm')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjm')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjm')
        ind3 = ResolvedVarNames.index('Vimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjm')
        ind3 = ResolvedVarNames.index('Uimj')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimj')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimj')
        ind3 = ResolvedVarNames.index('Vimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimj')
        ind3 = ResolvedVarNames.index('Uimjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uimjp')
        ind3 = ResolvedVarNames.index('Vijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vimjp')
        ind3 = ResolvedVarNames.index('Uijp')
        SETermsRef.append([ind1, ind2, ind3, -1])
    
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Uijp')
        ind3 = ResolvedVarNames.index('Vipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])
        ind1 = ResolvedVarNames.index('Vij')
        ind2 = ResolvedVarNames.index('Vijp')
        ind3 = ResolvedVarNames.index('Uipjp')
        SETermsRef.append([ind1, ind2, ind3, -1])

    return SETermsRef

# Get the names of all the terms (useful for debugging)
def createSETermsNames(ResolvedVarNames,SETermsRef):
    # Fill SETermsNames
    SETermsNames=[]
    for iref, ref in enumerate(SETermsRef):
        name1=''
        name2=''
        name3=''
        name4=''
        if not ref[0]==-1:
            name1=ResolvedVarNames[ref[0]]
        if not ref[1]==-1:
            name2=ResolvedVarNames[ref[1]]
        if not ref[2]==-1:
            name3=ResolvedVarNames[ref[2]]
        if not ref[3]==-1:
            name4=ResolvedVarNames[ref[3]]
        SETermsNames.append(name1+name2+name3+name4)
    
    return SETermsNames


def initSEModel(Case):
    ResolvedVarNames = createResolvedVarNames(Case)
    SETermsRef = createSETerms(ResolvedVarNames,Case)
    SETermsNames = createSETermsNames(ResolvedVarNames,SETermsRef)
    nTerms = len(SETermsRef)
    par.printRoot('nTerms used for Stochastic Estimation',nTerms)
    return ResolvedVarNames, SETermsRef, SETermsNames
